#ifndef __MEM_MAP_H__
#define __MEM_MAP_H__
/*FEE*/
#ifdef FEE_START_SEC_VAR_INIT_UNSPECIFIED
#pragma SET_DATA_SECTION("FEE_DATA_SECTION")
#undef FEE_START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef FEE_STOP_SEC_VAR_INIT_UNSPECIFIED
#pragma SET_DATA_SECTION()
#undef FEE_STOP_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef FEE_START_SEC_CONST_UNSPECIFIED
#pragma SET_DATA_SECTION("FEE_CONST_SECTION")
#undef FEE_START_SEC_CONST_UNSPECIFIED
#endif

#ifdef FEE_STOP_SEC_CONST_UNSPECIFIED
#pragma SET_DATA_SECTION()
#undef FEE_STOP_SEC_CONST_UNSPECIFIED
#endif

#ifdef FEE_START_SEC_CODE
#pragma SET_CODE_SECTION("FEE_TEXT_SECTION")
#undef FEE_START_SEC_CODE
#endif

#ifdef FEE_STOP_SEC_CODE
#pragma SET_CODE_SECTION()
#undef FEE_STOP_SEC_CODE
#endif


#endif  /* __MEM_MAP_H__ */
