/** @file pinmux.h 
*   @brief PINMUX Driver Implementation File
*   @date 29.May.2013
*   @version 03.05.02
*
*/

/* (c) Texas Instruments 2009-2013, All rights reserved. */

#ifndef __PINMUX_H__
#define __PINMUX_H__

#include "reg_pinmux.h"



#define PINMUX_PIN_3_SHIFT	16U
#define PINMUX_PIN_4_SHIFT	24U
#define PINMUX_PIN_6_SHIFT	8U
#define PINMUX_PIN_9_SHIFT	0U
#define PINMUX_PIN_14_SHIFT	24U
#define PINMUX_PIN_16_SHIFT	16U
#define PINMUX_PIN_22_SHIFT	0U
#define PINMUX_PIN_23_SHIFT	16U
#define PINMUX_PIN_24_SHIFT	24U
#define PINMUX_PIN_25_SHIFT	0U
#define PINMUX_PIN_30_SHIFT	8U
#define PINMUX_PIN_31_SHIFT	16U
#define PINMUX_PIN_32_SHIFT	0U
#define PINMUX_PIN_33_SHIFT	0U
#define PINMUX_PIN_35_SHIFT	16U
#define PINMUX_PIN_37_SHIFT	8U
#define PINMUX_PIN_38_SHIFT	16U
#define PINMUX_PIN_39_SHIFT	0U
#define PINMUX_PIN_40_SHIFT	8U
#define PINMUX_PIN_41_SHIFT	16U
#define PINMUX_PIN_54_SHIFT	8U
#define PINMUX_PIN_55_SHIFT	16U
#define PINMUX_PIN_86_SHIFT	0U
#define PINMUX_PIN_91_SHIFT	24U
#define PINMUX_PIN_92_SHIFT	0U
#define PINMUX_PIN_96_SHIFT	16U
#define PINMUX_PIN_97_SHIFT	24U
#define PINMUX_PIN_98_SHIFT	0U
#define PINMUX_PIN_99_SHIFT	8U
#define PINMUX_PIN_100_SHIFT	16U
#define PINMUX_PIN_105_SHIFT	24U
#define PINMUX_PIN_106_SHIFT	0U
#define PINMUX_PIN_107_SHIFT	8U
#define PINMUX_PIN_118_SHIFT	0U
#define PINMUX_PIN_124_SHIFT	16U
#define PINMUX_PIN_127_SHIFT	8U
#define PINMUX_PIN_130_SHIFT	16U
#define PINMUX_PIN_133_SHIFT	8U
#define PINMUX_PIN_1_SHIFT	0U
#define PINMUX_PIN_2_SHIFT	8U
#define PINMUX_PIN_5_SHIFT	0U
#define PINMUX_PIN_15_SHIFT	8U
#define PINMUX_PIN_125_SHIFT	8U
#define PINMUX_PIN_126_SHIFT	24U

#define PINMUX_GATE_EMIF_CLK_SHIFT			8U
#define PINMUX_GIOB_DISABLE_HET2_SHIFT		16U
#define PINMUX_ALT_ADC_TRIGGER_SHIFT		0U
#define PINMUX_ETHERNET_SHIFT				24U

#define PINMUX_PIN_3_MASK		(~(0xFFU << PINMUX_PIN_3_SHIFT)
#define PINMUX_PIN_4_MASK		(~(0xFFU << PINMUX_PIN_4_SHIFT)
#define PINMUX_PIN_6_MASK		(~(0xFFU << PINMUX_PIN_6_SHIFT)
#define PINMUX_PIN_9_MASK		(~(0xFFU << PINMUX_PIN_9_SHIFT)
#define PINMUX_PIN_14_MASK		(~(0xFFU << PINMUX_PIN_14_SHIFT)
#define PINMUX_PIN_16_MASK		(~(0xFFU << PINMUX_PIN_16_SHIFT)
#define PINMUX_PIN_22_MASK		(~(0xFFU << PINMUX_PIN_22_SHIFT)
#define PINMUX_PIN_23_MASK		(~(0xFFU << PINMUX_PIN_23_SHIFT)
#define PINMUX_PIN_24_MASK		(~(0xFFU << PINMUX_PIN_24_SHIFT)
#define PINMUX_PIN_25_MASK		(~(0xFFU << PINMUX_PIN_25_SHIFT)
#define PINMUX_PIN_30_MASK		(~(0xFFU << PINMUX_PIN_30_SHIFT)
#define PINMUX_PIN_31_MASK		(~(0xFFU << PINMUX_PIN_31_SHIFT)
#define PINMUX_PIN_32_MASK		(~(0xFFU << PINMUX_PIN_32_SHIFT)
#define PINMUX_PIN_33_MASK		(~(0xFFU << PINMUX_PIN_33_SHIFT)
#define PINMUX_PIN_35_MASK		(~(0xFFU << PINMUX_PIN_35_SHIFT)
#define PINMUX_PIN_37_MASK		(~(0xFFU << PINMUX_PIN_37_SHIFT)
#define PINMUX_PIN_38_MASK		(~(0xFFU << PINMUX_PIN_38_SHIFT)
#define PINMUX_PIN_39_MASK		(~(0xFFU << PINMUX_PIN_39_SHIFT)
#define PINMUX_PIN_40_MASK		(~(0xFFU << PINMUX_PIN_40_SHIFT)
#define PINMUX_PIN_41_MASK		(~(0xFFU << PINMUX_PIN_41_SHIFT)
#define PINMUX_PIN_54_MASK		(~(0xFFU << PINMUX_PIN_54_SHIFT)
#define PINMUX_PIN_55_MASK		(~(0xFFU << PINMUX_PIN_55_SHIFT)
#define PINMUX_PIN_86_MASK		(~(0xFFU << PINMUX_PIN_86_SHIFT)
#define PINMUX_PIN_91_MASK		(~(0xFFU << PINMUX_PIN_91_SHIFT)
#define PINMUX_PIN_92_MASK		(~(0xFFU << PINMUX_PIN_92_SHIFT)
#define PINMUX_PIN_96_MASK		(~(0xFFU << PINMUX_PIN_96_SHIFT)
#define PINMUX_PIN_97_MASK		(~(0xFFU << PINMUX_PIN_97_SHIFT)
#define PINMUX_PIN_98_MASK		(~(0xFFU << PINMUX_PIN_98_SHIFT)
#define PINMUX_PIN_99_MASK		(~(0xFFU << PINMUX_PIN_99_SHIFT)
#define PINMUX_PIN_100_MASK		(~(0xFFU << PINMUX_PIN_100_SHIFT)
#define PINMUX_PIN_105_MASK		(~(0xFFU << PINMUX_PIN_105_SHIFT)
#define PINMUX_PIN_106_MASK		(~(0xFFU << PINMUX_PIN_106_SHIFT)
#define PINMUX_PIN_107_MASK		(~(0xFFU << PINMUX_PIN_107_SHIFT)
#define PINMUX_PIN_118_MASK		(~(0xFFU << PINMUX_PIN_118_SHIFT)
#define PINMUX_PIN_124_MASK		(~(0xFFU << PINMUX_PIN_124_SHIFT)
#define PINMUX_PIN_127_MASK		(~(0xFFU << PINMUX_PIN_127_SHIFT)
#define PINMUX_PIN_130_MASK		(~(0xFFU << PINMUX_PIN_130_SHIFT)
#define PINMUX_PIN_133_MASK		(~(0xFFU << PINMUX_PIN_133_SHIFT)
#define PINMUX_PIN_1_MASK		(~(0xFFU << PINMUX_PIN_1_SHIFT)
#define PINMUX_PIN_2_MASK		(~(0xFFU << PINMUX_PIN_2_SHIFT)
#define PINMUX_PIN_5_MASK		(~(0xFFU << PINMUX_PIN_5_SHIFT)
#define PINMUX_PIN_15_MASK		(~(0xFFU << PINMUX_PIN_15_SHIFT)
#define PINMUX_PIN_125_MASK		(~(0xFFU << PINMUX_PIN_125_SHIFT)
#define PINMUX_PIN_126_MASK		(~(0xFFU << PINMUX_PIN_126_SHIFT)

#define PINMUX_GATE_EMIF_CLK_MASK		(~(0xFFU << PINMUX_GATE_EMIF_CLK_SHIFT))
#define PINMUX_GIOB_DISABLE_HET2_MASK	(~(0xFFU << PINMUX_GIOB_DISABLE_HET2_SHIFT))
#define PINMUX_ALT_ADC_TRIGGER_MASK		(~(0xFFU << PINMUX_ALT_ADC_TRIGGER_SHIFT))
#define PINMUX_ETHERNET_MASK			(~(0xFFU << PINMUX_ETHERNET_SHIFT))



#define PINMUX_PIN_3_MIBSPI3NCS_3		(0x1U <<  PINMUX_PIN_3_SHIFT)
#define PINMUX_PIN_3_I2C_SCL		(0x2U <<  PINMUX_PIN_3_SHIFT)
#define PINMUX_PIN_3_HET1_29		(0x4U <<  PINMUX_PIN_3_SHIFT)

#define PINMUX_PIN_4_MIBSPI3NCS_2		(0x1U <<  PINMUX_PIN_4_SHIFT)
#define PINMUX_PIN_4_I2C_SDA		(0x2U <<  PINMUX_PIN_4_SHIFT)
#define PINMUX_PIN_4_HET1_27		(0x4U <<  PINMUX_PIN_4_SHIFT)

#define PINMUX_PIN_6_HET1_11		(0x1U <<  PINMUX_PIN_6_SHIFT)
#define PINMUX_PIN_6_MIBSPI3NCS_4		(0x2U <<  PINMUX_PIN_6_SHIFT)
#define PINMUX_PIN_6_HET2_18		(0x4U <<  PINMUX_PIN_6_SHIFT)

#define PINMUX_PIN_9_GIOA_2		(0x1U <<  PINMUX_PIN_9_SHIFT)
#define PINMUX_PIN_9_HET2_0		(0x8U <<  PINMUX_PIN_9_SHIFT)

#define PINMUX_PIN_14_GIOA_5		(0x1U <<  PINMUX_PIN_14_SHIFT)
#define PINMUX_PIN_14_EXTCLKIN		(0x2U <<  PINMUX_PIN_14_SHIFT)

#define PINMUX_PIN_16_GIOA_6		(0x1U <<  PINMUX_PIN_16_SHIFT)
#define PINMUX_PIN_16_HET2_4		(0x2U <<  PINMUX_PIN_16_SHIFT)

#define PINMUX_PIN_22_GIOA_7		(0x1U <<  PINMUX_PIN_22_SHIFT)
#define PINMUX_PIN_22_HET2_6		(0x2U <<  PINMUX_PIN_22_SHIFT)

#define PINMUX_PIN_23_HET1_01		(0x1U <<  PINMUX_PIN_23_SHIFT)
#define PINMUX_PIN_23_SPI4NENA		(0x2U <<  PINMUX_PIN_23_SHIFT)
#define PINMUX_PIN_23_HET2_8		(0x10U <<  PINMUX_PIN_23_SHIFT)

#define PINMUX_PIN_24_HET1_03		(0x1U <<  PINMUX_PIN_24_SHIFT)
#define PINMUX_PIN_24_SPI4NCS_0		(0x2U <<  PINMUX_PIN_24_SHIFT)
#define PINMUX_PIN_24_HET2_10		(0x10U <<  PINMUX_PIN_24_SHIFT)

#define PINMUX_PIN_25_HET1_0		(0x1U <<  PINMUX_PIN_25_SHIFT)
#define PINMUX_PIN_25_SPI4CLK		(0x2U <<  PINMUX_PIN_25_SHIFT)

#define PINMUX_PIN_30_HET1_02		(0x1U <<  PINMUX_PIN_30_SHIFT)
#define PINMUX_PIN_30_SPI4SIMO		(0x2U <<  PINMUX_PIN_30_SHIFT)

#define PINMUX_PIN_31_HET1_05		(0x1U <<  PINMUX_PIN_31_SHIFT)
#define PINMUX_PIN_31_SPI4SOMI		(0x2U <<  PINMUX_PIN_31_SHIFT)
#define PINMUX_PIN_31_HET2_12		(0x4U <<  PINMUX_PIN_31_SHIFT)

#define PINMUX_PIN_32_MIBSPI5NCS_0		(0x1U <<  PINMUX_PIN_32_SHIFT)
#define PINMUX_PIN_32_DMM_DATA_5		(0x2U <<  PINMUX_PIN_32_SHIFT)

#define PINMUX_PIN_33_HET1_07		(0x1U <<  PINMUX_PIN_33_SHIFT)
#define PINMUX_PIN_33_HET2_14		(0x8U <<  PINMUX_PIN_33_SHIFT)

#define PINMUX_PIN_35_HET1_09		(0x1U <<  PINMUX_PIN_35_SHIFT)
#define PINMUX_PIN_35_HET2_16		(0x2U <<  PINMUX_PIN_35_SHIFT)

#define PINMUX_PIN_37_MIBSPI3NCS_1		(0x1U <<  PINMUX_PIN_37_SHIFT)
#define PINMUX_PIN_37_HET1_25		(0x2U <<  PINMUX_PIN_37_SHIFT)
#define PINMUX_PIN_37_MDCLK		(0x4U <<  PINMUX_PIN_37_SHIFT)

#define PINMUX_PIN_38_HET1_06		(0x1U <<  PINMUX_PIN_38_SHIFT)
#define PINMUX_PIN_38_SCIRX		(0x2U <<  PINMUX_PIN_38_SHIFT)

#define PINMUX_PIN_39_HET1_13		(0x1U <<  PINMUX_PIN_39_SHIFT)
#define PINMUX_PIN_39_SCITX		(0x2U <<  PINMUX_PIN_39_SHIFT)

#define PINMUX_PIN_40_MIBSPI1NCS_2		(0x1U <<  PINMUX_PIN_40_SHIFT)
#define PINMUX_PIN_40_HET1_19		(0x2U <<  PINMUX_PIN_40_SHIFT)
#define PINMUX_PIN_40_MDIO		(0x4U <<  PINMUX_PIN_40_SHIFT)

#define PINMUX_PIN_41_HET1_15		(0x1U <<  PINMUX_PIN_41_SHIFT)
#define PINMUX_PIN_41_MIBSPI1NCS_4		(0x2U <<  PINMUX_PIN_41_SHIFT)

#define PINMUX_PIN_54_MIBSPI3NENA		(0x1U <<  PINMUX_PIN_54_SHIFT)
#define PINMUX_PIN_54_MIBSPI3NCS_5		(0x2U <<  PINMUX_PIN_54_SHIFT)
#define PINMUX_PIN_54_HET1_31		(0x4U <<  PINMUX_PIN_54_SHIFT)

#define PINMUX_PIN_55_MIBSPI3NCS_0		(0x1U <<  PINMUX_PIN_55_SHIFT)
#define PINMUX_PIN_55_AD2EVT		(0x2U <<  PINMUX_PIN_55_SHIFT)
#define PINMUX_PIN_55_GIOB_2		(0x4U <<  PINMUX_PIN_55_SHIFT)

#define PINMUX_PIN_86_AD1EVT		(0x1U <<  PINMUX_PIN_86_SHIFT)
#define PINMUX_PIN_86_MII_RX_ER		(0x2U <<  PINMUX_PIN_86_SHIFT)
#define PINMUX_PIN_86_RMII_RX_ER		(0x4U <<  PINMUX_PIN_86_SHIFT)

#define PINMUX_PIN_91_HET1_24		(0x1U <<  PINMUX_PIN_91_SHIFT)
#define PINMUX_PIN_91_MIBSPI1NCS_5		(0x2U <<  PINMUX_PIN_91_SHIFT)
#define PINMUX_PIN_91_MII_RXD_0		(0x4U <<  PINMUX_PIN_91_SHIFT)
#define PINMUX_PIN_91_RMII_RXD_0		(0x8U <<  PINMUX_PIN_91_SHIFT)

#define PINMUX_PIN_92_HET1_26		(0x1U <<  PINMUX_PIN_92_SHIFT)
#define PINMUX_PIN_92_MII_RXD_1		(0x2U <<  PINMUX_PIN_92_SHIFT)
#define PINMUX_PIN_92_RMII_RXD_1		(0x4U <<  PINMUX_PIN_92_SHIFT)

#define PINMUX_PIN_96_MIBSPI1NENA		(0x1U <<  PINMUX_PIN_96_SHIFT)
#define PINMUX_PIN_96_HET1_23		(0x2U <<  PINMUX_PIN_96_SHIFT)
#define PINMUX_PIN_96_MII_RXD_2		(0x4U <<  PINMUX_PIN_96_SHIFT)

#define PINMUX_PIN_97_MIBSPI5NENA		(0x1U <<  PINMUX_PIN_97_SHIFT)
#define PINMUX_PIN_97_DMM_DATA_7		(0x2U <<  PINMUX_PIN_97_SHIFT)
#define PINMUX_PIN_97_MII_RXD_3		(0x4U <<  PINMUX_PIN_97_SHIFT)

#define PINMUX_PIN_98_MIBSPI5SOMI_0		(0x1U <<  PINMUX_PIN_98_SHIFT)
#define PINMUX_PIN_98_DMM_DATA_12		(0x2U <<  PINMUX_PIN_98_SHIFT)
#define PINMUX_PIN_98_MII_TXD_0		(0x4U <<  PINMUX_PIN_98_SHIFT)
#define PINMUX_PIN_98_RMII_TXD_0		(0x8U <<  PINMUX_PIN_98_SHIFT)

#define PINMUX_PIN_99_MIBSPI5SIMO_0		(0x1U <<  PINMUX_PIN_99_SHIFT)
#define PINMUX_PIN_99_DMM_DATA_8		(0x2U <<  PINMUX_PIN_99_SHIFT)
#define PINMUX_PIN_99_MII_TXD_1		(0x4U <<  PINMUX_PIN_99_SHIFT)
#define PINMUX_PIN_99_RMII_TXD_1		(0x8U <<  PINMUX_PIN_99_SHIFT)

#define PINMUX_PIN_100_MIBSPI5CLK		(0x1U <<  PINMUX_PIN_100_SHIFT)
#define PINMUX_PIN_100_DMM_DATA_4		(0x2U <<  PINMUX_PIN_100_SHIFT)
#define PINMUX_PIN_100_MII_TXEN		(0x4U <<  PINMUX_PIN_100_SHIFT)
#define PINMUX_PIN_100_RMII_TXEN		(0x8U <<  PINMUX_PIN_100_SHIFT)

#define PINMUX_PIN_105_MIBSPI1NCS_0		(0x1U <<  PINMUX_PIN_105_SHIFT)
#define PINMUX_PIN_105_MIBSPI1SOMI_1		(0x2U <<  PINMUX_PIN_105_SHIFT)
#define PINMUX_PIN_105_MII_TXD_2		(0x4U <<  PINMUX_PIN_105_SHIFT)

#define PINMUX_PIN_106_HET1_08		(0x1U <<  PINMUX_PIN_106_SHIFT)
#define PINMUX_PIN_106_MIBSPI1SIMO_1		(0x2U <<  PINMUX_PIN_106_SHIFT)
#define PINMUX_PIN_106_MII_TXD_3		(0x4U <<  PINMUX_PIN_106_SHIFT)

#define PINMUX_PIN_107_HET1_28		(0x1U <<  PINMUX_PIN_107_SHIFT)
#define PINMUX_PIN_107_MII_RXCLK		(0x2U <<  PINMUX_PIN_107_SHIFT)
#define PINMUX_PIN_107_RMII_REFCLK		(0x4U <<  PINMUX_PIN_107_SHIFT)
#define PINMUX_PIN_107_MII_RX_AVCLK4		(0x8U <<  PINMUX_PIN_107_SHIFT)

#define PINMUX_PIN_118_HET1_10		(0x1U <<  PINMUX_PIN_118_SHIFT)
#define PINMUX_PIN_118_MII_TX_CLK		(0x2U <<  PINMUX_PIN_118_SHIFT)
#define PINMUX_PIN_118_MII_TX_AVCLK4		(0x8U <<  PINMUX_PIN_118_SHIFT)

#define PINMUX_PIN_124_HET1_12		(0x1U <<  PINMUX_PIN_124_SHIFT)
#define PINMUX_PIN_124_MII_CRS		(0x2U <<  PINMUX_PIN_124_SHIFT)
#define PINMUX_PIN_124_RMII_CRS_DV		(0x4U <<  PINMUX_PIN_124_SHIFT)

#define PINMUX_PIN_127_HET1_30		(0x1U <<  PINMUX_PIN_127_SHIFT)
#define PINMUX_PIN_127_MII_RX_DV		(0x2U <<  PINMUX_PIN_127_SHIFT)

#define PINMUX_PIN_130_MIBSPI1NCS_1		(0x1U <<  PINMUX_PIN_130_SHIFT)
#define PINMUX_PIN_130_HET1_17		(0x2U <<  PINMUX_PIN_130_SHIFT)
#define PINMUX_PIN_130_MII_COL		(0x4U <<  PINMUX_PIN_130_SHIFT)

#define PINMUX_PIN_133_GIOB_1		(0x1U <<  PINMUX_PIN_133_SHIFT)

#define PINMUX_PIN_1_GIOB_3		(0x1U <<  PINMUX_PIN_1_SHIFT)

#define PINMUX_PIN_2_GIOA_0		(0x1U <<  PINMUX_PIN_2_SHIFT)

#define PINMUX_PIN_5_GIOA_1		(0x1U <<  PINMUX_PIN_5_SHIFT)

#define PINMUX_PIN_15_HET1_22		(0x1U <<  PINMUX_PIN_15_SHIFT)

#define PINMUX_PIN_125_HET1_14		(0x1U <<  PINMUX_PIN_125_SHIFT)

#define PINMUX_PIN_126_GIOB_0		(0x1U <<  PINMUX_PIN_126_SHIFT)

#define PINMUX_GATE_EMIF_CLK_ON                                 (0x0 <<  PINMUX_GATE_EMIF_CLK_SHIFT)      /**/ 
#define PINMUX_GIOB_DISABLE_HET2_ON                             (0x1U <<  PINMUX_GIOB_DISABLE_HET2_SHIFT)
#define PINMUX_GATE_EMIF_CLK_OFF                                (0x1U <<  PINMUX_GATE_EMIF_CLK_SHIFT)    
#define PINMUX_GIOB_DISABLE_HET2_OFF                            (0x0 <<  PINMUX_GIOB_DISABLE_HET2_SHIFT)
#define PINMUX_ALT_ADC_TRIGGER_1                                (0x1U <<  PINMUX_ALT_ADC_TRIGGER_SHIFT)
#define PINMUX_ALT_ADC_TRIGGER_2                                (0x2U <<  PINMUX_ALT_ADC_TRIGGER_SHIFT)
#define PINMUX_ETHERNET_MII                                     (0x0 <<  PINMUX_ETHERNET_SHIFT)
#define PINMUX_ETHERNET_RMII                                    (0x1U <<  PINMUX_ETHERNET_SHIFT)

/** @fn void muxInit(void)
*   @brief Initializes the PINMUX Driver
*
*   This function initializes the PINMUX module and configures the selected 
*   pinmux settings as per the user selection in the GUI
*/
void muxInit(void);

#endif
